export const skills = {
  languages: [
    'C#',
    'Python',
    'Java',
    'HTML',
    'CSS',
    'JavaScript',
    'TypeScript',
    'MATLAB',
  ],
  librariesAndFrameworks: [
    'React',
    'React Native',
    'Redux',
    'Bootstrap',
    'Next.js',
  ],
  data: ['SQL', 'Cosmos DB', 'Firebase DBs', 'Redis'],
  nonVisibleData: ['Firebase Realtime DB'],
  other: [
    'Git',
    'Latex',
    'Figma',
    'Android Studio',
    'Docker',
    'Node.js',
    'Linux',
  ],
  nonVisibleOther: ['Firebase Auth', 'Jest'],
}
