import 'bootstrap/dist/css/bootstrap.css'
import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React, { ReactNode } from 'react'
import '../../styles/globals.css'
import Links from './components/links'
import Navbar from './components/navbar'
import styles from './layout.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Libby',
  description: 'Generated by create next app',
}

type LayoutProps = {
  children: ReactNode
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./images/lola.png" />
      </head>
      <body className={styles.layout}>
        <Navbar />
        <div className="my-5">{children}</div>
        <Links />
      </body>
    </html>
  )
}

export default Layout
