import 'bootstrap/dist/css/bootstrap.css'
import { Metadata } from 'next'
import React, { ReactNode } from 'react'
import '../../styles/globals.css'
import Links from '../components/links'
import Navbar from '../components/navbar'
import styles from './layout.module.css'
import { Roboto, Inconsolata } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Libby',
  description: 'Generated by create next app',
}

type LayoutProps = {
  children: ReactNode
}

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--roboto',
})

const inconsolata = Inconsolata({
  weight: ['300', '400', '500', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--inconsolata',
})

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/goose.png" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css"
        />
      </head>
      <body
        className={`${styles.layout} ${roboto.variable} ${inconsolata.variable}`}
      >
        <Navbar />
        <div className="my-5">{children}</div>
        <Links />
      </body>
    </html>
  )
}

export default Layout
